name: 'Publish Blog Post'
description: 'Publishes blog post to Hashnode'
author: 'Johnkayode'


inputs:
  title:
    required: true
    description: 'Title of the post'
  subtitle:
    required: false
    description: 'Description of the post'
  cover_image:
    required: false
    description: 'Cover image url for the post'
  publication_id:
    required: true
    description: 'The ID of publication the post belongs to.'
  format:  
    description: 'Format of the content to be published [markdown, notion]'
    required: true
  source:
    description: 'File path (Markdown) or URL (Notion) of the content'
    required: true
  access_token:
    description: 'Hashnode developer access token'
    required: true
  notion_token:
    description: 'Notion integration token (only required if format is notion)'
    required: false

outputs:
  id:
    description: The ID of the new blog post.
  url:
    description: The URL of the new blog post.

runs:
  using: 'node20'
  main: 'dist/index.js'